FROM python:3.10
WORKDIR /app
EXPOSE 80
EXPOSE 8080
RUN pip3 install numpy
RUN pip3 install --upgrade setuptools
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0"]

